import java.util.*;
class SwitchAlphapbet{
		public static void main(String arg[]){
		Scanner ob = new Scanner(System.in);
		
		System.out.print(" Enter letter? ");
		char letter=ob.next().charAt(0);
		
		switch(letter){
			case'a':System.out.println("a for Apple");
			        break;
		    case'A':System.out.println("A for Apple");
			        break;
			case'b':System.out.println("b for Ball");
			        break;
            case'B':System.out.println("B for Ball");
			        break;
            case'c':System.out.println("c for Cat");
			        break;
            case'C':System.out.println("C for Cat");
			        break;
            case'd':System.out.println("d for Dog");
			        break;
            case'D':System.out.println("D for Dog");
			        break;
            case'e':System.out.println("e for Elephent");
			        break;
            case'E':System.out.println("E for Elephent");
			        break;
            case'f':System.out.println("f for Furniture");
			        break;
            case'F':System.out.println("F for Furniture");
			        break;
            case'g':System.out.println("g for Game");
			        break;
            case'G':System.out.println("G for Game");
			        break;
            case'h':System.out.println("h for House");
			        break;
            case'H':System.out.println("H for House");
			        break;
            case'i':System.out.println("i for Ice");
			        break;
            case'I':System.out.println("I for Ice");
			        break;
            case'j':System.out.println("j for Jug");
			        break;
            case'J':System.out.println("J for Jug");
			        break;
            case'k':System.out.println("k for Kite");
			        break;
            case'K':System.out.println("K for Kite");
			        break;
            case'l':System.out.println("l for Lemon");
			        break;
            case'L':System.out.println("L for Lemon");
			        break;
            case'm':System.out.println("m for Mouse");
			        break;
            case'M':System.out.println("M for Mouse");
			        break;
            case'n':System.out.println("n for Net");
			        break;
            case'N':System.out.println("N for Net");
			        break;
            case'o':System.out.println("o for Orange");
			        break;
            case'O':System.out.println("O for Orange");
			        break;
		    case'p':System.out.println("p for Pineapple");
			        break;
		    case'P':System.out.println("p for Pineapple");
			        break;
	        case'q':System.out.println("q for Quiz");
			        break;
		    case'Q':System.out.println("Q for Quiz");
			        break;
		    case'r':System.out.println("r for Roll");
			        break;
			case'R':System.out.println("R for Roll");
			        break;
			case's':System.out.println("s for Stairs");
			        break;
			case'S':System.out.println("S for Stairs");
			        break;
			case't':System.out.println("t for Tape");
			        break;
		    case'T':System.out.println("T for Tape");
			        break;
			case'u':System.out.println("u for Umbrella");
			        break;
			case'U':System.out.println("U for Umbrella");
			        break;
			case'v':System.out.println("v for Ven");
			        break;
			case'V':System.out.println("V for Ven");
			        break;
		    case'w':System.out.println("w for Waffer");
			        break;
			case'W':System.out.println("W for Waffer");
			        break;
			case'x':System.out.println("x for Xperia");
			        break;
			case'X':System.out.println(" X for Xperia");
			        break;
			case'y':System.out.println("y for Yellow");
			        break;
			case'Y':System.out.println("Y for Yellow");
			        break;
			case'z':System.out.println("z for 	Zebra");
			        break;
			case'Z':System.out.println("Z for Zebra");
			        break;
					
			       					
			default:System.out.println("Invalid letter");
		}
		}	
}		